### ISSUE TITLE
Manque le fichier discordconfig.json

### ISSUE THREAD

**Issue by itwars** [william-dandrea/vitemadose_scraper#1]
Bonjour,

Peux-tu nous mettre un exemple de ce fichier ?

Merci.

**Comment by william-dandrea** [comment]
Bonjour, ce fichier reste volontairement caché car il contient notre propre clé API. Le laisser en public générerais une faille de sécurité au niveau de notre serveur. Cependant, il contient juste une variable que vous pouvez trouver sur l'interface github
